apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ms-sum
  name: svc-sum
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: ms-sum
  type: ClusterIP
status:
  loadBalancer: {}
